[package]
name = "stabilizer"
version = "0.2.0"
authors = ["Robert Jördens <rj@quartiq.de>"]
description = "Firmware for the Sinara Stabilizer board (stm32h743, eth, poe, 2 adc, 2 dac)"
categories = ["embedded", "no-std", "hardware-support", "science"]
license = "GPL-3.0-or-later"
keywords = ["ethernet", "eth", "stm32", "stm32h7", "adc", "dac", "tcp", "no-std", "embedded"]
repository = "https://github.com/quartiq/stabilizer"
readme = "README.md"
documentation = "https://docs.rs/stabilizer/"
edition = "2018"
publish = false
exclude = [
	".travis.yml",
	".gitignore",
	"doc/",
	"doc/*"
]

[badges]
travis-ci = { repository = "quartiq/stabilizer", branch = "master" }
maintenance = { status = "experimental" }

[package.metadata.docs.rs]
features = []
default-target = "thumbv7em-none-eabihf"

[dependencies]
cortex-m = { version = "0.6", features = ["inline-asm", "const-fn"] }
cortex-m-rt = { version = "0.6", features = ["device"] }
cortex-m-log = { version = "0.6", features = ["log-integration"] }
log = "0.4"
panic-semihosting = { version = "0.5", optional = true }
panic-itm = { version = "0.4", optional = true }
serde = { version = "1.0", features = ["derive"], default-features = false }
heapless = { version = "0.5" }

[dependencies.serde-json-core]
# version = "0.0"
git = "https://github.com/quartiq/serde-json-core.git"
rev = "fc764de"

[dependencies.stm32h7]
version = "0.8"
features = ["stm32h743", "rt"]

[dependencies.smoltcp]
git = "https://github.com/m-labs/smoltcp.git"
rev = "1ada3da"
features = ["proto-ipv4", "socket-tcp"]
default-features = false

[dependencies.cortex-m-rtfm]
git = "https://github.com/japaric/cortex-m-rtfm"
rev = "da675dc3"

[features]
semihosting = ["panic-semihosting", "cortex-m-log/semihosting"]
itm = ["panic-itm", "cortex-m-log/itm"]
bkpt = [ ]

[profile.dev]
codegen-units = 1
incremental = false

[profile.release]
debug = true
lto = true
codegen-units = 1
