[package]
name = "serial-settings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniconf = "0.9"
menu = {path = "../../../rust-embedded-community/menu", features = ["echo"]}
heapless = "0.8"
embedded-io = "0.6"
log = {version = "0.4", default-features = false }
