//! Harmonic DDS Generator
//!
//! Implements a fixed-point Direct Digital Synthesis (DDS)
//! engine capable of generating a sum of N harmonics.
//!
//! Designed for deterministic, fast sample-by-sample waveform generation.

/// User-facing config for harmonic generator
/// 
/// - `zero_order_frequency`: Fundamental frequency (Hz)
/// - `amplitude`: Amplitude of each harmonic
/// - `phase`: Phase offset of each harmonic in cycles (0.0-1.0)
/// 
/// Amp and phase are in array for N harmonics where 0 - fundamental, etc.
#[derive(Copy, Clone, Debug)]
pub struct BasicConfig<const N: usize> {
    pub zero_order_frequency: f32,
    pub amplitude: [f32; N],
    pub phase: [f32; N]
}

// Default: 50Hz fundamental frequency, all amplitudes and phases set to 0
impl<const N: usize> Default for BasicConfig<N>{
    fn default() -> Self {
        Self {
            zero_order_frequency: 50.0,
            amplitude: [0.0;N],
            phase: [0.0;N],
        }
    }
}

/// Errors that may occur when converting a BasicConfig into internal fixed point config
#[derive(Copy, Clone, Debug)]
pub enum Error {
    // Amplitude exceeds i16 range after scaling
    InvalidAmplitude,
    // Frequency exceeds Nyquist limit
    InvalidFrequency,
}

impl<const N: usize> BasicConfig<N> {


    /// Converts floating point user config into fixed-point values suitabled for DDS generation
    /// 
    /// 
    /// - Validates frequency against Nyquist
    /// - Scales amplitudes to i16 range
    /// - Converts frequeency and phase into 32-bit phase accumulator space
    pub fn try_into_config(self, sample_period: f32, full_scale: f32)->Result<Config<N>, Error>{
        
        // Scale factor to convert cycles (0.0-1.0) into 32-bit phase space
        const PHASE_SCALE: f32 = (u32::MAX as f32) + 1.0;

        // Find phase increment (frequency tuning word) for each harmonic
        let ftw: [f32; N] = core::array::from_fn(|i| {
            self.zero_order_frequency
                * ((i + 1) as f32)
                * sample_period
                * PHASE_SCALE
        });

        // Ensure no harmonic exceeds Nyquist frequency
        let nyquist_hz = 1.0/(2.0*sample_period);
        for i in 0..N {
            let freq = self.zero_order_frequency * (i as f32 + 1.0);
            if freq > nyquist_hz {
                return Err(Error::InvalidFrequency);
            }
        }


        let phase_increment: [i32; N] = core::array::from_fn(|i| {ftw[i] as i32});
        
        // Convert floating point amplitudes into i16 values
        let amps_f32: [f32; N] = core::array::from_fn(|i: usize| {
            let scale = i16::MAX as f32 / full_scale;
            self.amplitude[i] * scale
        });

        for &amp in &amps_f32{
            if !(i16::MIN as f32..=i16::MAX as f32).contains(&amp){
                return Err(Error::InvalidAmplitude);
            }
        }

        let amps_i16: [i16; N] = core::array::from_fn(|i| {
            amps_f32[i] as i16
        });
        
        //Convert phase offsets (cycles) into 32-bit phase space
        let phases_i32: [i32; N] = core::array::from_fn(|i: usize| {
           let p =  self.phase[i] * ((u32::MAX as f32) + 1.0);
           
           p as i32
            
        });

        Ok(Config::<N> {
                amplitude: amps_i16,
                phase_increment,
                phase_offset: phases_i32})
    }

}

/// Internal fixed-point config used by generator
/// 
/// - `amplitude`: i16 amplitude per harmonic
/// - `phase_increment`: DDS phase step per sample
/// - `phase_offset`: Static phase offset in 32 bit phase space
#[derive(Copy, Clone, Debug)]
pub struct Config<const N: usize> {
    pub amplitude: [i16; N],
    pub phase_increment: [i32;N],
    pub phase_offset: [i32; N],
}

impl<const N: usize> Default for Config<N>{
    fn default() -> Self {
        Self {
            amplitude: [0;N],
            phase_increment: [0;N],
            phase_offset: [0;N],
        }
    }
}

///Multi-harmonic DDS signal generator
/// 
/// Each harmonic has its own:
///  - Phase accumulator
///  - Amplitude
///  - Phase offset
/// 
/// Output samples are generated by summing all harmonics
#[derive(Debug)]
pub struct HarmonicGenerator<const N: usize>{
    phase_accumulator: [i32;N],
    config: Config<N>,
}

impl<const N: usize> HarmonicGenerator<N> {

    /// Create a new harmonic generator with given config
    /// Phase accumulators start at 0
    pub fn new(config: Config<N>)-> Self {
        Self {
            config,
            phase_accumulator: [0;N],
        }
    }

    /// Replace waveform config (freq, amp, phase)
    /// Does not reset phase accumulator
    pub fn update_waveform(&mut self, new_config: Config<N>) {
        self.config = new_config;
    }

    /// Set the fundamental phase and per-sample phase increment.
    ///
    /// Harmonic `k` (0-based) is placed at `(k + 1)` times the fundamental
    /// phase and advances at `(k + 1)` times the fundamental increment, so
    /// all harmonics stay exactly phase-coherent with the fundamental.
    ///
    /// Intended to be called once per batch with the phase and frequency
    /// estimate of a PLL tracking an external reference (see [`idsp::RPLL`]).
    ///
    /// - `phase`: Fundamental phase at the first sample of the batch, in
    ///   32-bit phase space (`1 << 32` is one full cycle).
    /// - `increment`: Fundamental phase increment per sample, in 32-bit
    ///   phase space.
    pub fn set_fundamental(&mut self, phase: i32, increment: i32) {
        for i in 0..N {
            let harmonic = (i + 1) as i32;
            self.phase_accumulator[i] = phase.wrapping_mul(harmonic);
            self.config.phase_increment[i] = increment.wrapping_mul(harmonic);
        }
    }
}

/// Generate the next output sample
/// 
/// For each harmonic
///  - Add phase offset
///  - Compute sine value using phase accumulator
///  - Scale by amplitude
///  - Accumulate into final output
/// 
/// Use wrapping arthimetic for correct DDS behaviour
impl<const N: usize> core::iter::Iterator for HarmonicGenerator<N> {
    type Item = i16;
    fn next(&mut self) -> Option<i16>{

        let mut acc: i32 = 0;
        for i in 0..N
        {
            // Compute effective phase including offsets
            let phase = self.phase_accumulator[i].wrapping_add(self.config.phase_offset[i]);
            // Advance phase accumulator by freq * time between next() which is sample time
            self.phase_accumulator[i] = self.phase_accumulator[i].wrapping_add(self.config.phase_increment[i]);
            // Get sine from phase (fixed-point lookup)
            let scale = idsp::cossin(phase).1 >> 16;
            // Scale by samplitude and accumulate
            acc = acc.wrapping_add((self.config.amplitude[i] as i32 * scale) >> 15);
            

        }
        // Clamp final output to i16 rangfe
        let out = acc.clamp(i16::MIN as i32, i16::MAX as i32) as i16;
        Some(out)
    }
}